a = input(' digite algo: ')
print(' o tipo primitivo desse valor é ', type(a))
print('so tem espacos? ', a.isspace())
print(' e um numero? ', a.isnumeric())
print('e alfabetico? ', a.isalpha())
print('e alfanumerico ', a.isalnum())
print('e maiuscola', a.isupper())
print(' e minuscula', a.islower())
print('esta capitalizada', a.istitle())
